# These are supported funding model platforms

github: <b>test</b># Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: <b>test</b># Replace with a single Patreon username
open_collective: <b>test</b># Replace with a single Open Collective username
ko_fi: <b>test</b># Replace with a single Ko-fi username
tidelift: <b>test</b># Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: <b>test</b># Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: <b>test</b># Replace with a single Liberapay username
issuehunt: <b>test</b># Replace with a single IssueHunt username
lfx_crowdfunding: <b>test</b># Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: <b>test</b># Replace with a single Polar username
buy_me_a_coffee: <b>test</b># Replace with a single Buy Me a Coffee username
thanks_dev: <b>test</b>
custom: <b>test</b># Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
